survivor:
  target: default
  outputs:
    default:
      type: postgres
      host: "localhost"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      port: 5433
      schema: "public"
      threads: 4
      keepalives_idle: 0
