survivor:
  target: default
  outputs:
    default:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      port: "{{ env_var('PORT') | as_number }}"
      schema: "bronze"
      threads: 4
      keepalives_idle: 0
