-- Silver bridge for survivoR's castaway_scores metrics (season-level performance).
{{ config(materialized='table', schema='silver') }}

with source as (
    select
        version_season,
        castaway_id,
        score_overall,
        score_outwit,
        score_outplay,
        score_outlast,
        score_result,
        score_jury,
        score_vote,
        score_adv,
        score_inf,
        r_score_chal_all,
        r_score_chal_immunity,
        r_score_chal_individual,
        r_score_chal_individual_immunity,
        r_score_chal_reward,
        r_score_chal_team,
        r_score_chal_team_reward,
        r_score_chal_tribal,
        r_score_chal_tribal_immunity,
        r_score_chal_tribal_reward,
        r_score_chal_individual_reward,
        r_score_chal_team_immunity,
        r_score_chal_duel,
        p_score_chal_all,
        p_score_chal_immunity,
        p_score_chal_individual,
        p_score_chal_individual_immunity,
        p_score_chal_reward,
        p_score_chal_team,
        p_score_chal_team_reward,
        p_score_chal_tribal,
        p_score_chal_tribal_immunity,
        p_score_chal_tribal_reward,
        p_score_chal_individual_reward,
        p_score_chal_team_immunity,
        p_score_chal_duel,
        r_score_vote,
        p_score_vote,
        n_votes_received,
        n_successful_boots,
        p_successful_boot,
        n_tribals,
        n_tribals_with_vote,
        r_score_adv,
        p_score_adv,
        n_adv_played,
        n_adv_not_played,
        n_adv_found,
        n_idols_found,
        n_voted_out_with_adv,
        n_voted_out_with_idol
    from {{ source('bronze', 'castaway_scores') }}
),
castaway_map as (
    select castaway_id, castaway_key
    from {{ ref('dim_castaway') }}
),
season_map as (
    select version_season, season_key
    from {{ ref('dim_season') }}
)

select
    {{ dbt_utils.generate_surrogate_key(['source.version_season', 'source.castaway_id']) }} as castaway_score_key,
    cm.castaway_key,
    sm.season_key,
    source.castaway_id,
    source.version_season,
    source.score_overall,
    source.score_outwit,
    source.score_outplay,
    source.score_outlast,
    source.score_result,
    source.score_jury,
    source.score_vote,
    source.score_adv,
    source.score_inf,
    source.r_score_chal_all,
    source.r_score_chal_immunity,
    source.r_score_chal_individual,
    source.r_score_chal_individual_immunity,
    source.r_score_chal_reward,
    source.r_score_chal_team,
    source.r_score_chal_team_reward,
    source.r_score_chal_tribal,
    source.r_score_chal_tribal_immunity,
    source.r_score_chal_tribal_reward,
    source.r_score_chal_individual_reward,
    source.r_score_chal_team_immunity,
    source.r_score_chal_duel,
    source.p_score_chal_all,
    source.p_score_chal_immunity,
    source.p_score_chal_individual,
    source.p_score_chal_individual_immunity,
    source.p_score_chal_reward,
    source.p_score_chal_team,
    source.p_score_chal_team_reward,
    source.p_score_chal_tribal,
    source.p_score_chal_tribal_immunity,
    source.p_score_chal_tribal_reward,
    source.p_score_chal_individual_reward,
    source.p_score_chal_team_immunity,
    source.p_score_chal_duel,
    source.r_score_vote,
    source.p_score_vote,
    source.n_votes_received,
    source.n_successful_boots,
    source.p_successful_boot,
    source.n_tribals,
    source.n_tribals_with_vote,
    source.r_score_adv,
    source.p_score_adv,
    source.n_adv_played,
    source.n_adv_not_played,
    source.n_adv_found,
    source.n_idols_found,
    source.n_voted_out_with_adv,
    source.n_voted_out_with_idol,
    current_timestamp as created_at,
    current_timestamp as updated_at
from source
left join castaway_map cm on cm.castaway_id = source.castaway_id
left join season_map sm on sm.version_season = source.version_season;
