{{ config(materialized='view', schema='bronze') }}

select
    ingest_run_id,
    castaway_unique_id,
    version,
    version_season,
    season,
    full_name,
    castaway_id,
    castaway,
    age,
    city,
    state,
    episode,
    day,
    castaways_order,
    result,
    place,
    jury_status,
    original_tribe,
    jury,
    finalist,
    winner,
    acknowledge,
    ack_look,
    ack_speak,
    ack_gesture,
    ack_smile,
    ack_quote,
    ack_score,
    source_dataset,
    ingested_at
from {{ source('bronze', 'castaways') }};
